chain:
  key: arka_key
  chain-id: arka-local
  rpc-addr: http://127.0.0.1:26657
  grpc-addr: http://127.0.0.1:9090
  keyring-backend: test
  gas-adjustment: 1.5
  gas-prices: 0.11uarka
  min-gas-amount: 1111111
  key-directory: .daemon/keys
  debug: false
  timeout: 20s
  block-timeout: 10s
  output-format: json
  sign-mode: direct
  log-level: debug
  provider: http://localhost:8080
service:
  access-token-secret: a
  refresh-token-secret: r
  access-token-expiry: 2h
  refresh-token-expiry: 1m
  port: 8000
  cors:
  - '*'
