version: '3.8'

services:
  blockchain-node:
    image: 159.65.149.125:5000/arka1:latest
    container_name: blockchain-node
    restart: unless-stopped
    environment:
      - CHAIN_ID=arka-local
      - MONIKER=node1
      - MINIMUM_GAS_PRICE=0uarka
      - KEY_NAME=validator
    ports:
      - "26657:26657" # RPC
      - "26656:26656" # P2P
      - "1317:1317"   # REST API
    volumes:
#      - ./data:/root/.simapp
#      - ./config:/root/.simapp/config
      - ./entrypoint.sh:/entrypoint.sh:ro

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - app-network

    command: ["sh", "/entrypoint.sh"]

 # ipfs-node:
  #  image: alpine:latest
   # container_name: ipfs-node
    #restart: unless-stopped
    #volumes:
     # - ./ipfs.sh:/ipfs.sh:ro
    #command: ["sh", "/ipfs.sh"]

  agent-orchestrator:
    depends_on:
      - blockchain-node
    image: 159.65.149.125:5000/agent5:latest
    container_name: agent
    restart: no
    environment:
      - FILE="/go/src/github.com/arka-labs/agent-orchestrator/.agent-orchestrator/config.yaml"
      - CHAIN_ID="arka-devnet-1"
      - RPC_ADDR="http://blockchain-node:26657"  # This should point to the blockchain-node service
      - GRPC_ADDR="localhost:9090"
#      - FILE_SERVER="localhost:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./agent_setup.sh:/agent_setup.sh:rw
      - ./config.yaml:/go/src/github.com/arka-labs/agent-orchestrator/.agent-orchestrator/config.yaml
    networks:
      - app-network
#    command: ["sh", "-c", "./agent_setup.sh $FILE"]

    command: ["sh", "/agent_setup.sh"]

networks:
  app-network:
    driver: bridge
